### ISSUE TITLE
Sebuah pertanyaan

### ISSUE THREAD

**Issue by fakhrads** [dendense/polaris-laravel#1]
Apakah backend ini hanya memuat API saja? karena dari yang saya lihat, server untuk frontend dan backend nanti terpisah.

**Comment by dendense** [comment]
Betul Gans, hanya untuk pencanangan awal, untuk next development bakal
migrasi ke ExpressJS

**Comment by dendense** [comment]
Betul Gans, hanya untuk pencanangan awal, untuk next development bakal
migrasi ke ExpressJS
